#include<stdio.h>
#include<stdlib.h>
#include<conio.h>
#include<string.h>
#include<math.h>
#include<time.h>
#include <windows.h>

#define LEN sizeof(struct Book)
#define LEN1 sizeof(struct reader)
#define LEN2 sizeof(struct land)

typedef struct _Book {
    unsigned int id; //Book ID
    char* title; //book title
    char* authors; //comma separated list of authors
    unsigned int year; // year of publication
    unsigned int copies; //number of copies the library has
}Book;

typedef struct _BookArray {
    Book* array; // pointer to array (or linked list) of struct Book.
    unsigned int length; // number of elements in the (Book*) array
}BookArray;

struct reader //reader information
{
    int jnum;
    char jnam[20], time[20], tsnam[20];
    struct reader* next;
};
struct land//login information
{
    int account;
    char password[20];
    struct land* next;
};

//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE* file);

//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE* file);

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(Book book);

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(Book book);

//finds books with a given title.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_title(const char* title);

//finds books with the given authors.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_author(const char* author);

//finds books published in the given year.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_year(unsigned int year);

int tjzs();//satistics the number of book
void xg(int, char[]);
void mainmenu();//show the mainmenu
void tsmenu();//show the information of books
void jmenu();//show the borrow information
void lmenu();//show the login menu

void main1();//the function of mainmenu
void tsmain();//the function of book menu
void cxts();//find book
void zjts();//increase book
void scts();//delete book
void llts();//browse book
void xinjian();

void land();//login fuction system

void xgmm();//change the password
void lmain();//the function of the login

void lmenu()//the basic page
{


    printf("\n\n\t    Welcome to the library management system\n\n");
    printf("**********************************************");
    printf("\n\n\t\t1.Login\n\n");
    printf("\n\n\t\t2.Register a account\n\n");
    printf("\n\n\t\t3.Change the password\n\n");
    printf("\n\n\t\t4.Quit\n\n");
    printf("\n\n\t    Please input the number(1-4)\n");
    printf("**********************************************");
    return;
}





void lmain()//the fuction of login function
{


    char choose;
    lmenu();
    scanf(" %c", &choose);
    switch (choose)//功能函数
    {
        case'1':
            //land();
            break;
        case'2':
            xinjian();
            break;
        case'3':
            //xgmm();
            break;
        case'4':
            system("cls");
            getch();
            exit(0);
            system("cls");
            break;
    }

}


void xinjian() {
    FILE* fp;
    int j=0,i,jj=2;
    char account[20],  password[20], password1[20], usename[20];
    char hit = 0;
    if ((fp = fopen("land.txt","r"))==NULL)
    {
        fp = fopen("land.txt", "w");
        fclose(fp);
    }
    system("cls");
    fp = fopen("land.txt", "a");
    for (;;)//input twice password to avoid input wrong
    {
        printf("\nPlease input your name :");
        scanf("%s", account);

        printf("\nPlease input your password(less than 20 characters):");

        scanf("%s", password);
        printf("\nPlease input your password again:");
        scanf("%s", password1);


        if(strcmp(password, password1) != 0)
        {
            printf("There are different between twice input!Please register again!");
            hit = getch();
            if (hit = 27)
                system("cls");
            lmain();

        }
        else
        {
            printf("\nPlease input your usename(less than 20 characters):");
            scanf("%s", usename);
            fprintf(fp, "%s %s %s\n", account, password,usename);
            break;
        }
    }
    fclose(fp);
    printf("Dear %s,，your account has be built successfully",usename);
    getch();
    system("cls");
    lmain();
}



int main() {
    lmain();
}
